//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Metro.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RailWay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RailWay()
        {
            this.MonthlyTickets = new HashSet<MonthlyTicket>();
            this.StandarTickets = new HashSet<StandarTicket>();
            this.TicketSolds = new HashSet<TicketSold>();
        }
    
        public int Id { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> DepartureID { get; set; }
        public Nullable<int> DestinationID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int OwnedCompanyId { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonthlyTicket> MonthlyTickets { get; set; }
        public virtual Station Station { get; set; }
        public virtual Station Station1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StandarTicket> StandarTickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketSold> TicketSolds { get; set; }
    }
}
