//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Metro.Model
{
    using E_Metro.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class StandarTicket : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StandarTicket()
        {
            this.TicketSolds = new HashSet<TicketSold>();
        }
    
        public int Id { get; set; }
        private Nullable<int> _RailwayID;
        public Nullable<int> RailwayID { get => _RailwayID; set { _RailwayID = value; OnPropertyChanged(); } }
        private Nullable<System.DateTime> _DepartDate;
        public Nullable<System.DateTime> DepartDate { get => _DepartDate; set { _DepartDate = value; OnPropertyChanged(); } }
        private Nullable<System.TimeSpan> _DepartHour;
        public Nullable<System.TimeSpan> DepartHour { get => _DepartHour; set { _DepartHour = value; OnPropertyChanged(); } }
        public Nullable<int> IdType { get; set; }
    
        public virtual RailWay RailWay { get; set; }
        public virtual TicketType TicketType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketSold> TicketSolds { get; set; }
    }
}
